{% set version = '0.0-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assertive.reflection
  version: {{ version|replace("-", "_") }}

source:
  fn: assertive.reflection_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/assertive.reflection_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.reflection/assertive.reflection_{{ version }}.tar.gz
  sha256: 123672e1a99fc79e7e9e91566ee21bba1fb45fd13e353e41c52e3300ecd2f5a7

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_7
  run:
    - r-base
    - r-assertive.base >=0.0_7

test:
  commands:
    - $R -e "library('assertive.reflection')"           # [not win]
    - "\"%R%\" -e \"library('assertive.reflection')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.reflection
  license: GPL (>= 3)
  summary: A set of predicates and assertions for checking the state and capabilities of R, the
    operating system it is running on, and the IDE being used.  This is mainly for use
    by other package developers who want to include run-time testing features in their
    own packages. End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - jenzopr
