# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Mdrp+J9TgUzUT9sBfGfi8XL7L3/Gih+3NMSRO3NE8+Oy5lPJZdegNYwCufj82IPwrz1jlTEskqTo+6du5VD/lUyIkQ59LbPt7yTJOrz8pn+/W3NrJn2Y6dBNZRAklyY+rMaXSspomnYGMq4xqScBNYz/jXg1SSjEAA5dGefMcfE5UUNzJ0nnNe3p+1JBIiCctjPyTMF+cG/BnK+pR/ITbLJ/Kuti9mlkULLgBlteqLu5oYt7dMTULA9aT3AJP3Gel/bdMsOiNjDKU8De13NEd0xEHRLOLQ0wnnP/MPPtDzkImjBZdn5AJhqX/FbBwzYqTMPUhVU61MUDkK2xWlN3zfP9bD0RPMYKWb1xQbqrEr0I6ueUwfN1aoveoNOnAFjxf1O7YzQ8/mIZWkDsAwSWSw0P3hDOrAs4IyLRMCNps4J69si8faPkML5Tt3h3ge9g1PhgkQuWJtkVhbkUXal0e1LQeOmz3fwkWv2qHd5Qw9zPGy+z42SOXXkAWuDrOT2K3iuHLb5dgVU5InXRE3u8s5F7S3ZBV6vyTY2heo91APlQ+GiL5uYnUgXzoC/sBsvR8f3vJSBXLEZa+7BWof1xeiFsI9QWyE/wmJhsGheAWnvhjeyxPsUIuutHqrjTfLwDJu+f4vA2YBe3PRohPzMkFXy279P94BntBAeE9o1w8po="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
