appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Mdrp+J9TgUzUT9sBfGfi8XL7L3/Gih+3NMSRO3NE8+Oy5lPJZdegNYwCufj82IPwrz1jlTEskqTo+6du5VD/lUyIkQ59LbPt7yTJOrz8pn+/W3NrJn2Y6dBNZRAklyY+rMaXSspomnYGMq4xqScBNYz/jXg1SSjEAA5dGefMcfE5UUNzJ0nnNe3p+1JBIiCctjPyTMF+cG/BnK+pR/ITbLJ/Kuti9mlkULLgBlteqLu5oYt7dMTULA9aT3AJP3Gel/bdMsOiNjDKU8De13NEd0xEHRLOLQ0wnnP/MPPtDzkImjBZdn5AJhqX/FbBwzYqTMPUhVU61MUDkK2xWlN3zfP9bD0RPMYKWb1xQbqrEr0I6ueUwfN1aoveoNOnAFjxf1O7YzQ8/mIZWkDsAwSWSw0P3hDOrAs4IyLRMCNps4J69si8faPkML5Tt3h3ge9g1PhgkQuWJtkVhbkUXal0e1LQeOmz3fwkWv2qHd5Qw9zPGy+z42SOXXkAWuDrOT2K3iuHLb5dgVU5InXRE3u8s5F7S3ZBV6vyTY2heo91APlQ+GiL5uYnUgXzoC/sBsvR8f3vJSBXLEZa+7BWof1xeiFsI9QWyE/wmJhsGheAWnvhjeyxPsUIuutHqrjTfLwDJu+f4vA2YBe3PRohPzMkFXy279P94BntBAeE9o1w8po=}
