travis:
  secure:
    BINSTAR_TOKEN: T+k8DHxo/9R+VKopW6oAcVcLSh/eENok00kdg6MKXtjdtGUoTG+fqQshsAkQxm/q385QM8IJ5icxYJkLBVKopWPDKLr1uSJ5OVq2Nf49KMiXbPIzWuvPlUGfVcuMVXTBtc+5rUlMmW04WVzHE1TEJ4fiM4luBwbQzkQHuu38+TUPcrdUeCAb2jrOK4qelMm//4garwuCwzLGIz2j8+51ZWIDF0z/OjHSlOJpnQU0iFPDcWEWdjYYUCF3AdScuNKPhfGLu3PXMQZ0AjTqWYvlnFSIC3D72tchF6MaHIFu6dIKGBRzY5EUmUKOCo1h01BmnbJVVg0tlsCqhqbXsiNMjRZHt+XOgWGvMQmnM8KImh/CPrdZ9uTak71IJQWGJLfSDuqwuyy2pHwBAzdj5Nf9An3aYX/ArDff01hiU4tkkrNU+txElehaONMRen50Jwc1MDRFwaztRdbDOPik8L0Ug0ij71MC71NlG5JIW5xYCU+k4hyc5i7V+3yGuhWxAlsv67WQJGwBI5nAQBgQFYQQqk6EHwGV3qGwPyhSWQ/R85ch2jyYP8WWIm4mVti7BVKOx8/HGzchoA/60mBciQsS+YvPymU054IrXDBH7+yoRFCTBrpNuai1i40cr/HoFywVoFheUzw/VBrZUQV24bBiKynJE0/xOSXltfk3nSdfA4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
