travis:
  secure:
    BINSTAR_TOKEN: Z4Nh1wF9pAl3oFule9hn4TLk1PeBCKNthYPo8UPVa5S9dF0U5SbBKeH6IsJGhZCrmOIZI84dALYugxicv3xTxqd69vKnMzZaRNHLhBHGxiNwPjmfU2Ja/wC7lNeozzq44OATooeLO4bcCUvVYZAuu8Ylt9NdJ6FrgK8kEZWe0Swr+oo3jCdqNPYoUoG0En1TiBJ2TNtQlBygdYKChwYTivCWwgykCj/b11mpJUCZUbEBiStGl1a/YcSV0BxW8JWla19DIhYJbA1IcpxnbO8ugqlLOSki1nJiCyVHPx7gYBSqPS13/4YOzep6FD/38agjQ7J+PgFGNwy1N4Xyu3Tt2W0gmIuAxcCD6uajNtcunHx3EaKvnxk4k7WgIqs1DQ+By9azC/m+oDvkFXBsXYJd1z/9HHHWzi44p+rn3bv3EKBYJ/7tx5EEhmFJc3oLRdECntLICSamxh34+67bqkUoYQtdGHigpZWB/J4KXDy0HxKP/4tAwxfatv3CyQfZDIX+k5pExcTYV6q5OI1uyk6K8k+mXi+dtHz5L5idWMefmaCXxH5i6/p+npmZ/GVVq+XoYlooRCUBKNHQEQJRSIV6llMit/bNQGetPcyj0XDlVZfWZ5HihVJf8SbWa1Ers1mXQ34zB+evAus0R6Fxn1P6p6KZ6TARWoV3fZVHKXe/Gw8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
